# Convolutional Neural Networks (CNNs)
You should build an end-to-end machine learning pipeline using a convolutional neural network model. In particular, you should do the following:
- Load the `mnist` dataset using [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). You can find this dataset in the datasets folder.
- Split the dataset into training and test sets using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).
- Build an end-to-end machine learning pipeline, including a [convolutional neural network](https://keras.io/examples/vision/mnist_convnet/) model.
- Optimize your pipeline by validating your design decisions. 
- Test the best pipeline on the test set and report various [evaluation metrics](https://scikit-learn.org/0.15/modules/model_evaluation.html).  
- Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [1]:
import pandas as pd
import numpy as np

# TensorFlow and tf.keras
import tensorflow as tf
import keras

from tensorflow.keras import Sequential

from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.losses import KLDivergence

from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization

C:\Users\Blaq_Jesus\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df= pd.read_csv("mnist.csv")

In [3]:
df.drop('id', axis = 1, inplace = True)
df.head()

,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.describe()

,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
count,4000.000000,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,...,4000.000000,4000.000000,4000.000000,4000.000000,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0
mean,4.439500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.076750,0.015250,0.013000,0.001500,0.0,0.0,0.0,0.0,0.0,0.0
std,2.879655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.616022,0.964495,0.822192,0.094868,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,125.000000,61.000000,52.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0

### Splitting the data into Train and Test set

In [5]:
# Splitting the features into predictors and predictor
X = df.drop('class', axis = 1)
y = df['class']

In [6]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)
print(f'X trainset size {x_train.shape}')
print(f'X testset size {x_test.shape}')
print(f'y trainset size {y_train.shape}')
print(f'y testset size {y_test.shape}')

X trainset size (2800, 784)
X testset size (1200, 784)
y trainset size (2800,)
y testset size (1200,)

In [7]:
# # Reshaping each row of the train data into a 28 by 28 array with a dimension of 1

x_train = x_train.values.reshape(-1,28,28, 1)

In [8]:
x_train.shape

(2800, 28, 28, 1)

The description of the data shows that the maximum value for each column is __255__ and the minimum is __0__. To have the range of values between __0__ and __1__, the values could be simply divided by __255__.

In [9]:
# Scaling the data using the MinMax Scaler
x_train = x_train/255.0

In [10]:
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, 10)

## Building the Convolutional Model

In [11]:
model = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(10, activation="softmax"),
    ]
)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 32)        320

 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496

 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0
 2D)

 flatten (Flatten)           (None, 1600)              0

 dropout (Dropout)           (None, 1600)              0

 dense (Dense)               (None, 10)                16010

=================================================================
Total params: 34,826
Trainable params: 34,826
Non-trainable params: 0
_________________________________________________________________

In [12]:
batch_size = 100
epochs = 15

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/15
26/26 [==============================] - 1s 32ms/step - loss: 1.8685 - accuracy: 0.4230 - val_loss: 1.1017 - val_accuracy: 0.7393
Epoch 2/15
26/26 [==============================] - 1s 26ms/step - loss: 0.8160 - accuracy: 0.7508 - val_loss: 0.4193 - val_accuracy: 0.8750
Epoch 3/15
26/26 [==============================] - 1s 27ms/step - loss: 0.4913 - accuracy: 0.8437 - val_loss: 0.3019 - val_accuracy: 0.9143
Epoch 4/15
26/26 [==============================] - 1s 27ms/step - loss: 0.3546 - accuracy: 0.8873 - val_loss: 0.2220 - val_accuracy: 0.9393
Epoch 5/15
26/26 [==============================] - 1s 27ms/step - loss: 0.2949 - accuracy: 0.9099 - val_loss: 0.1886 - val_accuracy: 0.9536
Epoch 6/15
26/26 [==============================] - 1s 26ms/step - loss: 0.2356 - accuracy: 0.9258 - val_loss: 0.1620 - val_accuracy: 0.9536
Epoch 7/15
26/26 [==============================] - 1s 27ms/step - loss: 0.2142 - accuracy: 0.9302 - val_loss: 0.1389 - val_accuracy: 0.9643
Epoch 8/15
26/26 [==============================] - 1s 27ms/step - loss: 0.1889 - accuracy: 0.9409 - val_loss: 0.1248 - val_accuracy: 0.9607
Epoch 9/15
26/26 [==============================] - 1s 26ms/step - loss: 0.1701 - accuracy: 0.9472 - val_loss: 0.1187 - val_accuracy: 0.9643
Epoch 10/15
26/26 [==============================] - 1s 26ms/step - loss: 0.1418 - accuracy: 0.9567 - val_loss: 0.1026 - val_accuracy: 0.9679
Epoch 11/15
26/26 [==============================] - 1s 27ms/step - loss: 0.1307 - accuracy: 0.9544 - val_loss: 0.1110 - val_accuracy: 0.9607
Epoch 12/15
26/26 [==============================] - 1s 31ms/step - loss: 0.1285 - accuracy: 0.9579 - val_loss: 0.0941 - val_accuracy: 0.9714
Epoch 13/15
26/26 [==============================] - 1s 28ms/step - loss: 0.1155 - accuracy: 0.9623 - val_loss: 0.0857 - val_accuracy: 0.9714
Epoch 14/15
26/26 [==============================] - 1s 27ms/step - loss: 0.1096 - accuracy: 0.9631 - val_loss: 0.0863 - val_accuracy: 0.9679
Epoch 15/15
26/26 [==============================] - 1s 29ms/step - loss: 0.0991 - accuracy: 0.9655 - val_loss: 0.0829 - val_accuracy: 0.9750

## Predicting using the Test set

In [13]:
x_test = x_test.values.reshape(-1,28,28, 1)

# convert class vectors to binary class matrices
y_test = keras.utils.to_categorical(y_test, 10)

In [14]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 16.29332733154297
Test accuracy: 0.9641666412353516